#!/usr/bin/env bash
# GENERATED BY CLAUDE TO AUTOMATE GATHERING REPORT DATA
# =============================================================================
# run_all.sh -- exhaustive test sweep for Program 1 (OpenMP SpMV: CSR & ELL)
#
# What it runs, per matrix:
#   * sequential baselines           ./spmv-csr, ./spmv-ell
#   * OpenMP CSR and OpenMP ELL, for every combination of
#         threads x schedule   for partition=row
#         threads only         for partition=nnz  (the schedule has no effect
#                                                  with nnz partitioning, so it
#                                                  is run once as "static" and
#                                                  recorded as schedule "any")
#     (defaults: threads 1 2 4 8 16; schedules static dynamic,16 dynamic,64
#                dynamic,256 guided)
#
# Every run gets a big header (index, matrix, config, exact command) and two
# blank lines of gap before it. Results are parsed into results/results.tsv,
# and a summary (tables for report items 2b / 2c / 2d / 2e) is printed at the
# end and saved to results/summary.txt.
#
# Usage (on a compute node, NOT the login node; -c must cover the max threads):
#   srun -n 1 -c 16 ./run_all.sh            # full sweep (~250 runs)
#   QUICK=1 srun -n 1 -c 16 ./run_all.sh    # reduced sweep (threads 1 4 8,
#                                           #   schedules static/dynamic,64/guided)
#   ./run_all.sh --summary                  # re-print summary from results.tsv
#
# Env overrides (all optional):
#   MATDIR=matrices  OUT=results  TIMEOUT=600 (sec per run)  BAL_T=8
#   MATRIX_LIST="ecology2 heart1"   THREAD_LIST="1 2 4 8 16"
#   SCHED_LIST="static dynamic,64 guided"   PART_LIST="row nnz"
# =============================================================================
set -u

# ----------------------------- configuration ---------------------------------
MATDIR=${MATDIR:-matrices}
OUT=${OUT:-results}
TIMEOUT=${TIMEOUT:-600}
BAL_T=${BAL_T:-8}          # thread count used for the load-balance / winner tables

if [[ -n ${QUICK:-} ]]; then
  _T="1 4 8";       _S="static dynamic,64 guided"
else
  _T="1 2 4 8 16";  _S="static dynamic,16 dynamic,64 dynamic,256 guided"
fi
read -ra MATRICES  <<< "${MATRIX_LIST:-ecology2 atmosmodd lp_wood1p heart1}"
read -ra THREADS_L <<< "${THREAD_LIST:-$_T}"
read -ra SCHEDS    <<< "${SCHED_LIST:-$_S}"
read -ra PARTS     <<< "${PART_LIST:-row nnz}"

SUMMARY_ONLY=0
[[ ${1:-} == --summary ]] && SUMMARY_ONLY=1

mkdir -p "$OUT"
TSV="$OUT/results.tsv"

hr() { printf '%*s\n' 78 '' | tr ' ' "$1"; }

# ------------------------------ summary --------------------------------------
print_predict() {
  hr '='; echo " PREDICT STEP: row-length statistics, format footprint, modelled imbalance"
  echo " (computed directly from the .mtx files; symmetric files are expanded;"
  echo "  4-byte values + 4-byte indices;  imbalance model uses T=$BAL_T threads)"
  hr '='
  printf '%-10s %9s %9s %10s %7s %6s %8s %12s %12s %8s %8s %9s %9s  %s\n' \
    matrix m n nnz avg K K/avg CSR_bytes ELL_bytes ELL/CSR pad% rowImb nnzImb predict
  awk -F'\t' 'NR==1{next} {printf "%-10s %9d %9d %10d %7.2f %6d %8.2f %12d %12d %8.2f %7.1f%% %9.3f %9.3f  %s\n", \
      $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14}' "$OUT/predict.tsv"
  echo
  echo " rowImb = max/avg nnz per thread under schedule(static), row-based split (1.00 = perfect)"
  echo " nnzImb = same under an nnz-balanced contiguous split (model)"
  echo " predict: ELL if K/avg <= 1.5 else CSR (simple heuristic -- justify/refine in the report)"
  echo
  local f
  if compgen -G "$OUT/storage_*.txt" > /dev/null; then
    echo " Program-reported storage (from the sequential ELL run, to cross-check the table above):"
    for f in "$OUT"/storage_*.txt; do
      echo "   --- $(basename "$f" .txt | sed 's/^storage_//')"; sed 's/^/   /' "$f"
    done
  fi
}

print_summary() {
  [[ -f $TSV ]] || { echo "no $TSV -- run the sweep first"; return 1; }
  local ML TL SL PL
  ML=$(awk -F'\t' 'NR>1 && !s[$1]++ {printf "%s ", $1}' "$TSV")
  TL=$(awk -F'\t' 'NR>1 && $3 ~ /^[0-9]+$/ && !s[$3]++ {print $3}' "$TSV" | sort -n | tr '\n' ' ')
  SL=$(awk -F'\t' 'NR>1 && $4!="-" && $4!="any" && !s[$4]++ {printf "%s ", $4}' "$TSV")
  PL=$(awk -F'\t' 'NR>1 && $5!="-" && !s[$5]++ {printf "%s ", $5}' "$TSV")

  echo; echo
  hr '#'; echo "#  SUMMARY   (matrices: $ML)"; hr '#'
  echo "  cores available at run time: $(cat "$OUT/cores.txt" 2>/dev/null || echo '?')" \
       "  (thread counts above this are oversubscribed -> treat with care)"

  echo; echo
  [[ -f $OUT/predict.tsv ]] && { print_predict; echo; echo; }

  # ---- 1. sequential + winner at BAL_T ----------------------------------------
  hr '='; echo " [1] WINNER PER MATRIX  (best OpenMP config at $BAL_T threads vs sequential)  -- report 2d"; hr '='
  awk -F'\t' -v ML="$ML" -v T="$BAL_T" '
    NR==1 {next}
    $9=="PASS" || $9=="base" {
      if ($2=="csr-seq") sc[$1]=$6
      else if ($2=="ell-seq") se[$1]=$6
      else if ($3==T) {
        if ($2=="csr-omp" && (!($1 in bc) || $6+0 < bc[$1]+0)) { bc[$1]=$6; bcf[$1]=($5=="nnz" ? "nnz" : $4"/"$5) }
        if ($2=="ell-omp" && (!($1 in be) || $6+0 < be[$1]+0)) { be[$1]=$6; bef[$1]=($5=="nnz" ? "nnz" : $4"/"$5) }
      }
    }
    END {
      printf "%-10s %11s %11s | %13s %-16s | %13s %-16s | %-6s %8s\n", "matrix","csr-seq ms","ell-seq ms","best csr-omp","(sched/part)","best ell-omp","(sched/part)","winner","margin"
      n = split(ML, M, " ")
      for (i = 1; i <= n; i++) {
        m = M[i]
        if (!(m in bc) || !(m in be)) { printf "%-10s   (incomplete data)\n", m; continue }
        w = (bc[m] <= be[m]) ? "CSR" : "ELL"
        r = (bc[m] <= be[m]) ? be[m]/bc[m] : bc[m]/be[m]
        printf "%-10s %11s %11s | %13s %-16s | %13s %-16s | %-6s %7.2fx\n", m, sc[m], se[m], bc[m], bcf[m], be[m], bef[m], w, r
      }
    }' "$TSV"

  # ---- 2. throughput ----------------------------------------------------------
  echo; echo
  hr '='; echo " [2] THROUGHPUT of the best configs at $BAL_T threads  -- report 2e(b)"
  echo "     NOTE: for ELL the GB/s figure includes padding traffic; GFLOP/s counts only useful flops."; hr '='
  awk -F'\t' -v ML="$ML" -v T="$BAL_T" '
    NR==1 {next}
    $9=="PASS" || $9=="base" {
      if ($2=="csr-seq") { sg[$1,"c"]=$7; sb[$1,"c"]=$8 }
      else if ($2=="ell-seq") { sg[$1,"e"]=$7; sb[$1,"e"]=$8 }
      else if ($3==T) {
        k = ($2=="csr-omp") ? "c" : "e"
        if (!(($1,k) in bt) || $6+0 < bt[$1,k]+0) { bt[$1,k]=$6; og[$1,k]=$7; ob[$1,k]=$8 }
      }
    }
    END {
      printf "%-10s | %-19s | %-19s | %-19s | %-19s\n", "matrix", "csr-seq GF/s  GB/s", "ell-seq GF/s  GB/s", "csr-omp GF/s  GB/s", "ell-omp GF/s  GB/s"
      n = split(ML, M, " ")
      for (i = 1; i <= n; i++) { m = M[i]
        printf "%-10s | %9s %9s | %9s %9s | %9s %9s | %9s %9s\n", m, sg[m,"c"], sb[m,"c"], sg[m,"e"], sb[m,"e"], og[m,"c"], ob[m,"c"], og[m,"e"], ob[m,"e"] }
    }' "$TSV"

  # ---- 3. load balance --------------------------------------------------------
  echo; echo
  hr '='; echo " [3] LOAD BALANCING at $BAL_T threads: row vs nnz partition x schedule -- report 2c"
  echo "     nnz partitioning is schedule-independent, so it is a single row per kernel"; hr '='
  awk -F'\t' -v ML="$ML" -v SL="$SL" -v T="$BAL_T" '
    NR==1 {next}
    $3==T && $9=="PASS" { t[$1,$2,$4,$5]=$6 }
    function cell(v, b) { if (v=="" ) return "-"; if (b=="") return v; return sprintf("%s (%.2fx)", v, b/v) }
    END {
      nm = split(ML, M, " "); ns = split(SL, S, " ")
      kk[1]="csr-omp"; kk[2]="ell-omp"
      for (i = 1; i <= nm; i++) for (j = 1; j <= 2; j++) {
        m = M[i]; k = kk[j]; base = t[m,k,"static","row"]
        printf "\n -- %s / %s\n", m, k
        printf "    %-26s %22s\n", "partition / schedule", "time ms (vs static/row)"
        for (s = 1; s <= ns; s++)
          printf "    row / %-20s %22s\n", S[s], cell(t[m,k,S[s],"row"], base)
        printf "    nnz / %-20s %22s\n", "(any schedule)", cell(t[m,k,"any","nnz"], base)
      }
    }' "$TSV"

  # ---- 4. scaling -------------------------------------------------------------
  echo; echo
  hr '='; echo " [4] STRONG SCALING: S(t)=T1/Tt and E(t)=S/t (cell = S/E%)  -- report 2d"; hr '='
  awk -F'\t' -v ML="$ML" -v TL="$TL" -v SL="$SL" -v PL="$PL" '
    NR==1 {next}
    $9=="PASS" && $3 ~ /^[0-9]+$/ { t[$1,$2,$4,$5,$3]=$6 }
    END {
      nm = split(ML, M, " "); nt = split(TL, TT, " "); ns = split(SL, S, " "); np = split(PL, P, " ")
      kk[1]="csr-omp"; kk[2]="ell-omp"
      for (i = 1; i <= nm; i++) for (j = 1; j <= 2; j++) {
        m = M[i]; k = kk[j]
        printf "\n -- %s / %s\n    %-14s %-5s", m, k, "schedule", "part"
        for (a = 1; a <= nt; a++) printf " %13s", "t=" TT[a]
        printf "\n"
        for (p = 1; p <= np; p++) {
          lim = (P[p] == "nnz") ? 1 : ns
          for (s = 1; s <= lim; s++) {
            sk = (P[p] == "nnz") ? "any" : S[s]
            t1 = t[m,k,sk,P[p],TT[1]]; if (t1 == "") continue
            printf "    %-14s %-5s", (P[p] == "nnz" ? "(any)" : S[s]), P[p]
            for (a = 1; a <= nt; a++) {
              tv = t[m,k,sk,P[p],TT[a]]
              if (tv == "") printf " %13s", "-"
              else { sp = t1/tv; printf " %13s", sprintf("%.2f/%.0f%%", sp, 100*sp/TT[a]) }
            }
            printf "\n"
          }
        }
      }
    }' "$TSV"

  # ---- 5. problems ------------------------------------------------------------
  echo; echo
  hr '='; echo " [5] PROBLEMS (any run whose check is not PASS/base)"; hr '='
  local bad
  bad=$(awk -F'\t' 'NR>1 && $9!="PASS" && $9!="base" {printf "  %-10s %-8s t=%-3s sched=%-12s part=%-4s -> %s\n", $1,$2,$3,$4,$5,$9}' "$TSV")
  if [[ -z $bad ]]; then echo "  none: all runs PASSed."; else echo "$bad"; fi

  echo; echo
  hr '-'
  echo " Map to report:  2b <- [predict table]   2c <- [3]   2d <- [1],[4]   2e(b) <- [2]   2e(d) <- predict vs [1]"
  echo " Raw data: $TSV   |   full log: $OUT/run_all.log"
  hr '-'
}

if [[ $SUMMARY_ONLY -eq 1 ]]; then
  print_summary | tee "$OUT/summary.txt"
  exit 0
fi

# ------------------------------ preflight ------------------------------------
exec > >(tee "$OUT/run_all.log") 2>&1

missing=0
for b in ./spmv-csr ./spmv-ell ./spmv-omp-csr ./spmv-omp-ell; do
  [[ -x $b ]] || { echo "ERROR: $b not found/executable. Build it first, e.g.:"
                   echo "       gcc -fopenmp -O3 -o spmv-omp-csr spmv-omp-csr.c -lm"; missing=1; }
done
[[ $missing -eq 1 ]] && exit 1

MATS_OK=()
for m in "${MATRICES[@]}"; do
  if [[ -f $MATDIR/$m.mtx ]]; then MATS_OK+=("$m"); else echo "WARNING: $MATDIR/$m.mtx missing -- skipping"; fi
done
[[ ${#MATS_OK[@]} -eq 0 ]] && { echo "ERROR: no matrices found in $MATDIR"; exit 1; }

CORES=${SLURM_CPUS_PER_TASK:-$(env -u OMP_NUM_THREADS -u OMP_THREAD_LIMIT nproc)}
echo "$CORES" > "$OUT/cores.txt"
N_NNZ=0; N_OTHER=0
for p in "${PARTS[@]}"; do [[ $p == nnz ]] && N_NNZ=$((N_NNZ + 1)) || N_OTHER=$((N_OTHER + 1)); done
PER_THREAD=$(( N_OTHER * ${#SCHEDS[@]} + N_NNZ ))    # nnz partition: 1 run, schedule irrelevant
TOTAL=$(( ${#MATS_OK[@]} * (2 + 2 * ${#THREADS_L[@]} * PER_THREAD) ))

echo; hr '#'
echo "#  SpMV full sweep   $(date)"
echo "#  host=$(hostname)  cores=$CORES  timeout=${TIMEOUT}s/run"
echo "#  matrices : ${MATS_OK[*]}"
echo "#  threads  : ${THREADS_L[*]}"
echo "#  schedules: ${SCHEDS[*]}"
echo "#  partition: ${PARTS[*]}   (nnz runs once per thread count; schedule ignored)"
echo "#  total runs: $TOTAL"
hr '#'
for t in "${THREADS_L[@]}"; do
  [[ $t -gt $CORES ]] && echo "#  WARNING: t=$t > $CORES cores -> those runs are oversubscribed (request more with srun -c)"
done

# ------------------------------ predict --------------------------------------
predict_all() {
  printf 'matrix\tm\tn\tnnz\tavg\tK\tratio\tcsr_B\tell_B\tell_over_csr\tpad_pct\trow_imb\tnnz_imb\tpredicted\n' > "$OUT/predict.tsv"
  local mat
  for mat in "${MATS_OK[@]}"; do
    awk -v name="$mat" -v T="$BAL_T" '
      NR==1 { h = tolower($0); sym = (h ~ /symmetric|hermitian|skew/); next }
      /^%/  { next }
      !got  { m = $1 + 0; n = $2 + 0; got = 1; next }
      { i = $1 + 0; j = $2 + 0; c[i]++; nz++; if (sym && i != j) { c[j]++; nz++ } }
      END {
        if (nz == 0 || m == 0) exit
        K = 0
        for (r = 1; r <= m; r++) if (c[r] + 0 > K) K = c[r] + 0
        avg = nz / m
        csr = 8 * nz + 4 * (m + 1)
        ell = 8 * m * K
        pad = (m * K - nz) / (m * K) * 100
        chunk = int((m + T - 1) / T); cum = 0
        for (r = 1; r <= m; r++) {
          v = c[r] + 0
          a = int((r - 1) / chunk); if (a >= T) a = T - 1; sr[a] += v
          b = int(cum * T / nz);    if (b >= T) b = T - 1; sn[b] += v
          cum += v
        }
        mr = 0; mn = 0
        for (t = 0; t < T; t++) { if (sr[t] + 0 > mr) mr = sr[t]; if (sn[t] + 0 > mn) mn = sn[t] }
        ideal = nz / T
        printf "%s\t%d\t%d\t%d\t%.2f\t%d\t%.2f\t%d\t%d\t%.2f\t%.1f\t%.3f\t%.3f\t%s\n", \
               name, m, n, nz, avg, K, K/avg, csr, ell, ell/csr, pad, mr/ideal, mn/ideal, (K/avg <= 1.5 ? "ELL" : "CSR")
      }' "$MATDIR/$mat.mtx" >> "$OUT/predict.tsv"
  done
}

echo; echo; hr '='; echo " Computing predict-step statistics from the .mtx files ..."; hr '='
predict_all
print_predict

# ------------------------------ run one case ---------------------------------
CASE=0
printf 'matrix\tkernel\tthreads\tsched\tpart\tms\tgflops\tgbs\tcheck\n' > "$TSV"
RE='[:][[:space:]]*([0-9.eE+-]+)[[:space:]]*ms[[:space:]]*\([[:space:]]*([0-9.eE+-]+)[[:space:]]*GFLOP/s[[:space:]]+([0-9.eE+-]+)[[:space:]]*GB/s'

run_case() {
  local mat=$1 kern=$2 thr=$3 sch=$4 par=$5
  local file="$MATDIR/$mat.mtx" env_t=1 desc note="" cmd=()
  case $kern in
    csr-seq) cmd=(./spmv-csr "$file"); desc="sequential CSR"; thr="-"; sch="-"; par="-" ;;
    ell-seq) cmd=(./spmv-ell "$file"); desc="sequential ELL"; thr="-"; sch="-"; par="-" ;;
    csr-omp) cmd=(./spmv-omp-csr "$file" "--threads=$thr" "--schedule=$sch" "--partition=$par"); env_t=$thr
             desc="OpenMP CSR | threads=$thr | schedule=$sch | partition=$par" ;;
    ell-omp) cmd=(./spmv-omp-ell "$file" "--threads=$thr" "--schedule=$sch" "--partition=$par"); env_t=$thr
             desc="OpenMP ELL | threads=$thr | schedule=$sch | partition=$par" ;;
  esac
  local rec_sch=$sch
  if [[ $par == nnz && $kern == *-omp ]]; then
    rec_sch="any"; desc="${desc/schedule=$sch/schedule=$sch (irrelevant for nnz)}"
  fi
  CASE=$((CASE + 1))
  [[ $env_t -gt $CORES ]] && note="   [!! $env_t threads > $CORES cores: oversubscribed]"

  echo; echo
  hr '='
  printf ' [%03d/%03d]  %s  |  %s%s\n' "$CASE" "$TOTAL" "$mat" "$desc" "$note"
  printf ' $ OMP_NUM_THREADS=%s %s\n' "$env_t" "${cmd[*]}"
  hr '='

  local out rc ms="" gf="" gb="" check bench
  out=$(env OMP_NUM_THREADS="$env_t" timeout "$TIMEOUT" "${cmd[@]}" 2>&1); rc=$?
  echo "$out"

  bench=$(grep -m1 'benchmarking' <<< "$out")
  if [[ $bench =~ $RE ]]; then ms=${BASH_REMATCH[1]}; gf=${BASH_REMATCH[2]}; gb=${BASH_REMATCH[3]}; fi
  check=$(grep -m1 'correctness' <<< "$out" | grep -oE 'PASS|FAIL' | head -1)
  [[ -z $check && $kern == csr-seq ]] && check="base"
  [[ -z $check ]] && check="n/a"
  if   [[ $rc -eq 124 ]]; then check="TIMEOUT"
  elif [[ $rc -ne 0 || -z $ms ]]; then check="ERROR(rc=$rc)"; fi
  [[ -z $ms ]] && { ms="NaN"; gf="NaN"; gb="NaN"; }

  [[ $kern == ell-seq ]] && grep -E '^(file=|storage:|padding:)' <<< "$out" > "$OUT/storage_$mat.txt"

  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$mat" "$kern" "$thr" "$rec_sch" "$par" "$ms" "$gf" "$gb" "$check" >> "$TSV"
  printf ' -> time=%s ms | %s GFLOP/s | %s GB/s | check=%s\n' "$ms" "$gf" "$gb" "$check"
}

# ------------------------------ the sweep ------------------------------------
for mat in "${MATS_OK[@]}"; do
  echo; echo; echo
  hr '#'; echo "#  MATRIX: $mat"
  awk -F'\t' -v m="$mat" '$1==m {printf "#  m=%d  nnz=%d  avg=%.2f  K(max)=%d  K/avg=%.2f  ELL/CSR=%.2f  padding=%.1f%%  -> predicted winner: %s\n", $2,$4,$5,$6,$7,$10,$11,$14}' "$OUT/predict.tsv"
  hr '#'

  run_case "$mat" csr-seq - - -
  run_case "$mat" ell-seq - - -
  for kern in csr-omp ell-omp; do
    for thr in "${THREADS_L[@]}"; do
      for par in "${PARTS[@]}"; do
        if [[ $par == nnz ]]; then
          run_case "$mat" "$kern" "$thr" static "$par"      # schedule has no effect with nnz
        else
          for sch in "${SCHEDS[@]}"; do
            run_case "$mat" "$kern" "$thr" "$sch" "$par"
          done
        fi
      done
    done
  done
done

# ------------------------------ summary --------------------------------------
print_summary | tee "$OUT/summary.txt"
